language: python

python:
  - "3.6"

env:
  - DJANGO_VERSION=2.0.2

install: 
  - pip install codecov
  - pip install Django==$DJANGO_VERSION
  - mkdir -vp /home/travis/build/tystakartografen/cogs3/logs

addons:
  firefox: "60.0"
script:
  - pip install -r requirements.txt
  - coverage run manage.py test

after_success:
  - codecov
