language: python

python:
  - "3.6"

env:
  - DJANGO_VERSION=2.0.2

install: 
  - pip install codecov
  - pip install Django==$DJANGO_VERSION

script:
  - pip install -r requirements.txt
  - coverage run manage.py test

after_success:
  - codecov
