language: python

python:
  - "3.6"

env:
  - DJANGO_VERSION=2.0.2
  - GECKO_DRIVER_VERSION=0.20.1

before_install:
  # Setup X to allow non-headless browsers to run
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

  # Install geckodriver
  - wget https://github.com/mozilla/geckodriver/releases/download/v${GECKO_DRIVER_VERSION}/geckodriver-v${GECKO_DRIVER_VERSION}-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v${GECKO_DRIVER_VERSION}-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install: 
  - pip install codecov
  - mkdir -vp /home/travis/build/tystakartografen/cogs3/logs

addons:
  firefox: "60.0"

script:
  - pip install -r requirements.txt
  - coverage run manage.py test

after_success:
  - codecov
